### ISSUE TITLE
Completely unusable on latest Atmosphere at 16.0.2. Dead project?

### ISSUE THREAD

**Issue by george2781** [J-D-K/Avatool#10]
This project hasn't been updated in ages, yet I'm making this issue regardless.
Running Avatool under applet mode (unsurprisingly) drops error 2168-0002
Running Avatool under title-override causes a 'the software was closed because an error occured' dialog
I have tried the following:
- [X] Downloading the latest pre-release
- [X] Compiling avatool from source with the latest libnx

**Comment by q1378659137** [comment]
I found a usable version here
-
https://gbatemp.net/threads/avatool-homebrew-tool-to-change-avatars.525654/post-10093889

**Comment by catfromplan9** [comment]
> ## I found a usable version here
> 
> https://gbatemp.net/threads/avatool-homebrew-tool-to-change-avatars.525654/post-10093889

kernel panic
