### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Nate-GIS** [J-D-K/Avatool#4]
So, long story short. I set a 1920 x 1080 picture as my profile picture in Goldleaf. I didn't know there was a 256 x 256 size limit. A new update was just pushed for Goldleaf, with an image size verifier. 

I can't open my user page to change my picture (crashes if I tap to change picture). I can't play any of my games, it crashes before the select a user page shows up.

I can see my new profile picture in Checkpoint. Though from the user page, my icon is a large white box. 

I tried your program. But the moment I press A to continue, it immediately crashes.

**Comment by J-D-K** [comment]
Sorry, I didn't see this. Did you get your problem fixed/sorted?

**Comment by Abrar1233** [comment]
hey i have the same exact problem as that dude any help would be appreciated
