### ISSUE TITLE
Does not work on HOS version 9

### ISSUE THREAD

**Issue by null-von-sushi** [J-D-K/Avatool#5]
Pressing A does absolutely nothing. I think this may be due to the changes in version 9?
Apparently a lot of homebrew needs to be rebuilt with newer versions of libnx.

**Comment by TheDeadCPU** [comment]
If anyone is here trying to find out how to get it to work on later HOS
There is a working fixed version here: https://gbatemp.net/threads/avatool-homebrew-tool-to-change-avatars.525654/page-3#post-8906548
