### ISSUE TITLE
Switch crashes instantly

### ISSUE THREAD

**Issue by Axodique** [J-D-K/Avatool#7]
I can run the app, but when I press A, the switch crashes instantly not letting me change my avatar first.

The crash said 0100000000001000 (themes) was responsible for the crash, so I deleted it and tried again, but now it says 010000000000002F which doesn't seem to exist in my contents folder.

**Comment by J-D-K** [comment]
That's a system module on the switch itself. Avatool was always a hacky workaround way to change avatars. It was only made to simplify the process after I stumbled upon where they're stored with JKSV. I'm not sure there is anything I can do to prevent crashing. 

I know there's got to be another way to pull it off. I just never had time to really look into it.

**Comment by Kupie** [comment]
Using JK's build from gbatemp fixed it for me https://gbatemp.net/threads/avatool-homebrew-tool-to-change-avatars.525654/page-3#post-8906548

**Comment by Axodique** [comment]
Ok nvm I was just stupid and used a png. Sorry.

**Comment by Axodique** [comment]
Well it still crashes before I can change the pic but now it crashes after shutting down the service.

**Comment by Axodique** [comment]
.... nvm again I just didn't understand how avatool worked.

**Comment by Axodique** [comment]
In the end it worked, thank you so much for this tool.
